# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [7]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [9]:

grades = np.array([56, 75, 76, 64, 65, 87])

print(grades)


[56 75 76 64 65 87]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [18]:
costs_matrix = np.array([
    [12, 52, 56, 92],
    [11, 50, 57, 95],
    [13, 49, 55, 90]
])

print(costs_matrix)

[[12 52 56 92]
 [11 50 57 95]
 [13 49 55 90]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [20]:
typeOfGrades = print(grades.dtype)
typeOfCostsMatrix = print(costs_matrix.dtype)

int64
int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [21]:
grades_shape = print(grades.shape)
cost_matrix_shape = print(costs_matrix.shape)

(6,)
(3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [24]:
sales_growth = np.linspace(0, 1000.5, 7)
print(sales_growth)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [35]:
vertical = np.array([1, 4, 6, 8, 9])
horizontal = np.array([11, 14, 12, 15, 16])

vertical_stack = np.vstack((vertical, horizontal))
horizontal_stack = np.hstack((vertical, horizontal))

print(vertical,"\t", horizontal, "\n")
print(vertical_stack,"\t", horizontal_stack)

[1 4 6 8 9] 	 [11 14 12 15 16] 

[[ 1  4  6  8  9]
 [11 14 12 15 16]] 	 [ 1  4  6  8  9 11 14 12 15 16]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [14]:
array = np.array([[1, 4], [5, 6]])
transposed = np.transpose(array)

print(array)
print(transposed)

[[1 4]
 [5 6]]
[[1 5]
 [4 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [19]:
array1 = np.array([[4, 5], [6, 2]])
array2 = np.array([[3, 1], [8, 7]])

elementwise_addition = array1 + array2
elementwise_sub = array1 - array2
scalar_mult = array1 * 2
elementwise_mult = array1 * array2
matrix_mult = np.dot(array1, array2)

print(elementwise_addition, "\n")
print(elementwise_sub, "\n")
print(scalar_mult, "\n")
print(elementwise_mult, "\n")
print(matrix_mult)

[[ 7  6]
 [14  9]] 

[[ 1  4]
 [-2 -5]] 

[[ 8 10]
 [12  4]] 

[[12  5]
 [48 14]] 

[[52 39]
 [34 20]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [20]:
matrix = np.array([
    [1, 4, 2],
    [3, 5, 7],
    [4, 8, 9]
])

min_value = np.min(matrix)
max_value = np.max(matrix)
sum_values = np.sum(matrix)
min_per_row = np.min(matrix, axis=1)
max_per_column = np.max(matrix, axis=0)

print(min_value, max_value, sum_values, min_per_row, max_per_column)


1 9 43 [1 3 4] [4 8 9]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [21]:
matrix = np.array([
    [5, 3, 8],
    [3, 8, 8],
    [5, 3, 2]
])

unique_values, frequencies = np.unique(matrix, return_counts=True)

print(unique_values, "\n")
print(frequencies)

[2 3 5 8] 

[1 3 2 3]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [22]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [23]:
data = {
    "Last Name": ["Ivanenko", "Petrenko", "Sydorenko", "Kovalenko"],
    "First Name": ["Ivan", "Petro", "Olha", "Marina"],
    "Date of Birth": ["1990-01-15", "1985-07-20", "1992-03-12", "1988-09-30"],
    "Weight (kg)": [70, 82, 65, None],
    "Health Insurance": [True, False, True, True],
}

df = pd.DataFrame(data)

print("Test DataFrame:")
print(df)

print("\nData types for each column:")
print(df.dtypes)


Test DataFrame:
   Last Name First Name Date of Birth  Weight (kg)  Health Insurance
0   Ivanenko       Ivan    1990-01-15         70.0              True
1   Petrenko      Petro    1985-07-20         82.0             False
2  Sydorenko       Olha    1992-03-12         65.0              True
3  Kovalenko     Marina    1988-09-30          NaN              True

Data types for each column:
Last Name            object
First Name           object
Date of Birth        object
Weight (kg)         float64
Health Insurance       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

14. Отримайте інформацію про форму датафрейму.

15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

16. Отримайте статистику для колонок числового типу.

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

**місце для текстової відповіді**

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.