# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [7]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [9]:

grades = np.array([56, 75, 76, 64, 65, 87])

print(grades)


[56 75 76 64 65 87]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [18]:
costs_matrix = np.array([
    [12, 52, 56, 92],
    [11, 50, 57, 95],
    [13, 49, 55, 90]
])

print(costs_matrix)

[[12 52 56 92]
 [11 50 57 95]
 [13 49 55 90]]


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [20]:
typeOfGrades = print(grades.dtype)
typeOfCostsMatrix = print(costs_matrix.dtype)

int64
int64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [21]:
grades_shape = print(grades.shape)
cost_matrix_shape = print(costs_matrix.shape)

(6,)
(3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [24]:
sales_growth = np.linspace(0, 1000.5, 7)
print(sales_growth)

[   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [35]:
vertical = np.array([1, 4, 6, 8, 9])
horizontal = np.array([11, 14, 12, 15, 16])

vertical_stack = np.vstack((vertical, horizontal))
horizontal_stack = np.hstack((vertical, horizontal))

print(vertical,"\t", horizontal, "\n")
print(vertical_stack,"\t", horizontal_stack)

[1 4 6 8 9] 	 [11 14 12 15 16] 

[[ 1  4  6  8  9]
 [11 14 12 15 16]] 	 [ 1  4  6  8  9 11 14 12 15 16]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [14]:
array = np.array([[1, 4], [5, 6]])
transposed = np.transpose(array)

print(array)
print(transposed)

[[1 4]
 [5 6]]
[[1 5]
 [4 6]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [19]:
array1 = np.array([[4, 5], [6, 2]])
array2 = np.array([[3, 1], [8, 7]])

elementwise_addition = array1 + array2
elementwise_sub = array1 - array2
scalar_mult = array1 * 2
elementwise_mult = array1 * array2
matrix_mult = np.dot(array1, array2)

print(elementwise_addition, "\n")
print(elementwise_sub, "\n")
print(scalar_mult, "\n")
print(elementwise_mult, "\n")
print(matrix_mult)

[[ 7  6]
 [14  9]] 

[[ 1  4]
 [-2 -5]] 

[[ 8 10]
 [12  4]] 

[[12  5]
 [48 14]] 

[[52 39]
 [34 20]]


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [20]:
matrix = np.array([
    [1, 4, 2],
    [3, 5, 7],
    [4, 8, 9]
])

min_value = np.min(matrix)
max_value = np.max(matrix)
sum_values = np.sum(matrix)
min_per_row = np.min(matrix, axis=1)
max_per_column = np.max(matrix, axis=0)

print(min_value, max_value, sum_values, min_per_row, max_per_column)


1 9 43 [1 3 4] [4 8 9]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [21]:
matrix = np.array([
    [5, 3, 8],
    [3, 8, 8],
    [5, 3, 2]
])

unique_values, frequencies = np.unique(matrix, return_counts=True)

print(unique_values, "\n")
print(frequencies)

[2 3 5 8] 

[1 3 2 3]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [2]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [23]:
data = {
    "Last Name": ["Ivanenko", "Petrenko", "Sydorenko", "Kovalenko"],
    "First Name": ["Ivan", "Petro", "Olha", "Marina"],
    "Date of Birth": ["1990-01-15", "1985-07-20", "1992-03-12", "1988-09-30"],
    "Weight (kg)": [70, 82, 65, None],
    "Health Insurance": [True, False, True, True],
}

df = pd.DataFrame(data)

print("Test DataFrame:")
print(df)

print("\nData types for each column:")
print(df.dtypes)


Test DataFrame:
   Last Name First Name Date of Birth  Weight (kg)  Health Insurance
0   Ivanenko       Ivan    1990-01-15         70.0              True
1   Petrenko      Petro    1985-07-20         82.0             False
2  Sydorenko       Olha    1992-03-12         65.0              True
3  Kovalenko     Marina    1988-09-30          NaN              True

Data types for each column:
Last Name            object
First Name           object
Date of Birth        object
Weight (kg)         float64
Health Insurance       bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [3]:
file_path = "missile_attacks_daily.csv"
df = pd.read_csv(file_path)
print("Missile Attacks DataFrame:")
print(df.head())
print("\nData types for each column:")
print(df.dtypes)


Missile Attacks DataFrame:
         time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   

                                        launch_place       target carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine     NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine     NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine     NaN   
3                 Bryansk oblast and Voronezh oblast  Kyiv oblast     NaN   
4                                      Rostov oblast      Ukraine     NaN   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      61.0         43            15.0                   NaN          NaN   
1

# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [4]:
print("First 10 rows of the DataFrame:")
print(df.head(10))

First 10 rows of the DataFrame:
         time_start          time_end             model  \
0  2025-01-18 20:00  2025-01-19 09:00    Shahed-136/131   
1  2025-01-17 19:00  2025-01-18 08:00    Shahed-136/131   
2  2025-01-16 19:00  2025-01-17 09:00    Shahed-136/131   
3  2025-01-16 19:00  2025-01-17 09:00  Iskander-M/KN-23   
4  2025-01-16 19:00  2025-01-17 09:00        Iskander-M   
5  2025-01-15 20:00  2025-01-16 09:00    Shahed-136/131   
6  2025-01-15 06:00  2025-01-15 08:00         X-59/X-69   
7  2025-01-15 06:00  2025-01-15 08:00         X-22/X-32   
8  2025-01-15 06:00  2025-01-15 08:00       X-101/X-555   
9  2025-01-15 06:00  2025-01-15 08:00            Kalibr   

                                        launch_place       target  carrier  \
0      Bryansk oblast and Oryol oblast and Millerovo      Ukraine      NaN   
1  Primorsko-Akhtarsk and Bryansk oblast and Mill...      Ukraine      NaN   
2  Primorsko-Akhtarsk and Kursk oblast and Bryans...      Ukraine      NaN   
3     

14. Отримайте інформацію про форму датафрейму.

In [5]:
print("Shape of the DataFrame:")
print(df.shape)

Shape of the DataFrame:
(2044, 16)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [6]:
print("Information about each column:")
df.info()

Information about each column:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2044 entries, 0 to 2043
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2044 non-null   object 
 1   time_end              2044 non-null   object 
 2   model                 2044 non-null   object 
 3   launch_place          1023 non-null   object 
 4   target                2016 non-null   object 
 5   carrier               225 non-null    object 
 6   launched              2041 non-null   float64
 7   destroyed             2044 non-null   int64  
 8   not_reach_goal        157 non-null    float64
 9   cross_border_belarus  32 non-null     float64
 10  back_russia           34 non-null     float64
 11  still_attacking       28 non-null     float64
 12  destroyed_details     294 non-null    object 
 13  launched_details      4 non-null      object 
 14  launch_place_details  4 non-null      obj

16. Отримайте статистику для колонок числового типу.

In [7]:
print("Statistics for numeric columns:")
print(df.describe())

Statistics for numeric columns:
          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2041.000000  2044.000000      157.000000             32.000000   
mean     10.609995     7.491683       20.828025              2.312500   
std      21.041038    14.190972       19.877245              2.054696   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.000000              1.000000   
50%       2.000000     1.000000       16.000000              2.000000   
75%       9.000000     7.000000       30.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    34.000000        28.000000  
mean      2.000000         2.821429  
std       1.154701         2.931989  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         4.000000  
max   

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [8]:
unique_counts = df.nunique()

# Finding the column with the least unique values
min_unique_column = unique_counts.idxmin()

print(f"Column with the least unique values: {min_unique_column}")
print(f"Unique values and their counts in '{min_unique_column}':")
print(df[min_unique_column].value_counts())

Column with the least unique values: launched_details
Unique values and their counts in 'launched_details':
launched_details
{'X-101/X-555': 50, 'Kalibr': 12}                     1
{'X-101/X-555': 55, 'Kalibr': 24, 'Iskander-K': 7}    1
{'X-101/X-555': 57, 'Kalibr': 28}                     1
{'X-101/X-555': 77, 'Kalibr': 28, 'X-59/X-69': 10}    1
Name: count, dtype: int64


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

**місце для текстової відповіді**

1.   Конвертація типів даних: пеереконатися, що типи даних колонок відповідають їх значенню. Наприклад, колонка з датами повинна мати тип datetime, а числові дані — типи int або float.
2.  Перевірка на пропущені значення: метод .info() дозволяє дізнатися, чи є пропущені значення в колонках. Якщо такі є, варто вирішити, чи слід видаляти ці рядки, чи заповнювати пропущені значення за допомогою певної стратегії (наприклад, середнє або медіана для числових даних). 
3. Перевірка на некоректні або аномальні значення: виявлення аномальних значень, таких як нулі або значення, що не відповідають контексту (наприклад, дуже великі або дуже малі значення, якщо вони не мають сенсу в контексті).


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [9]:
df['launched'] = df['launched'].astype('Int64')
print(f"Data type of 'launched' column: {df['launched'].dtype}")

Data type of 'launched' column: Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [10]:
threshold = 0.3 * len(df)
df_cleaned = df.dropna(axis=1, thresh=threshold)
print("Columns after removing those with less than 30% non-null values:")
print(df_cleaned)

Columns after removing those with less than 30% non-null values:
            time_start          time_end               model  \
0     2025-01-18 20:00  2025-01-19 09:00      Shahed-136/131   
1     2025-01-17 19:00  2025-01-18 08:00      Shahed-136/131   
2     2025-01-16 19:00  2025-01-17 09:00      Shahed-136/131   
3     2025-01-16 19:00  2025-01-17 09:00    Iskander-M/KN-23   
4     2025-01-16 19:00  2025-01-17 09:00          Iskander-M   
...                ...               ...                 ...   
2039  2022-10-01 12:00  2022-10-01 12:00            Orlan-10   
2040        2022-09-30        2022-09-30            Orlan-10   
2041  2022-09-29 23:00  2022-09-29 23:59      Shahed-136/131   
2042        2022-09-28        2022-09-28                X-59   
2043        2022-09-28        2022-09-28  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and 

21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [12]:
print(df.columns)

Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'carrier',
       'launched', 'destroyed', 'not_reach_goal', 'cross_border_belarus',
       'back_russia', 'still_attacking', 'destroyed_details',
       'launched_details', 'launch_place_details', 'source'],
      dtype='object')


In [16]:
df['time_start'] = pd.to_datetime(df['time_start'], errors='coerce', dayfirst=True) # If dates are in different formats, errors='coerce' will set invalid dates to NaT
df['time_end'] = pd.to_datetime(df['time_end'], errors='coerce', dayfirst=True)
print(df[['time_start', 'time_end']].isna().sum())
df['attack_duration'] = (df['time_end'] - df['time_start']).dt.total_seconds()
df_cleaned = df.drop_duplicates()
df_cleaned = df_cleaned[df_cleaned['attack_duration'] > 0]
df_cleaned.reset_index(drop=True, inplace=True)
rows_removed = len(df) - len(df_cleaned)
print(f"Rows removed: {rows_removed}")
print(f"Cleaned DataFrame shape: {df_cleaned.shape}")

time_start    1445
time_end       677
dtype: int64
Rows removed: 1610
Cleaned DataFrame shape: (434, 17)


C:\Users\psycho\AppData\Local\Temp\ipykernel_11728\3559650792.py:8: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['time_start'] = pd.to_datetime(df['time_start'], errors='coerce', dayfirst=True)
C:\Users\psycho\AppData\Local\Temp\ipykernel_11728\3559650792.py:9: UserWarning: Parsing dates in %Y-%m-%d %H:%M format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['time_end'] = pd.to_datetime(df['time_end'], errors='coerce', dayfirst=True)


**місце для текстової відповіді**

Щоб визначити, скільки рядків було видалено, можна порівняти кількість рядків у початковому датафреймі з кількістю рядків після очищення

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [17]:
missing_data_rows = df[df.isna().any(axis=1)]
print(missing_data_rows)

              time_start            time_end               model  \
0    2025-01-18 20:00:00 2025-01-19 09:00:00      Shahed-136/131   
1    2025-01-17 19:00:00 2025-01-18 08:00:00      Shahed-136/131   
2    2025-01-16 19:00:00 2025-01-17 09:00:00      Shahed-136/131   
3    2025-01-16 19:00:00 2025-01-17 09:00:00    Iskander-M/KN-23   
4    2025-01-16 19:00:00 2025-01-17 09:00:00          Iskander-M   
...                  ...                 ...                 ...   
2039 2022-10-01 12:00:00 2022-10-01 12:00:00            Orlan-10   
2040                 NaT                 NaT            Orlan-10   
2041 2022-09-29 23:00:00 2022-09-29 23:59:00      Shahed-136/131   
2042                 NaT                 NaT                X-59   
2043                 NaT                 NaT  Reconnaissance UAV   

                                           launch_place  \
0         Bryansk oblast and Oryol oblast and Millerovo   
1     Primorsko-Akhtarsk and Bryansk oblast and Mill...   
2     